name: CI

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch: {}

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      CI: true
      BAZELISK_ALLOW_ENVS: Y
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Bazel
        uses: actions/cache@v4
        with:
          path: ~/.cache/bazel
          key: bazel-${{ runner.os }}-${{ hashFiles('.bazelversion', 'MODULE.bazel', 'MODULE.bazel.lock') }}
          restore-keys: |
            bazel-${{ runner.os }}-

      - name: Build core library & docs targets
        run: bazel build //core:all --keep_going

  core-test:
    name: Tests
    runs-on: ubuntu-latest
    needs: build
    env:
      CI: true
      BAZELISK_ALLOW_ENVS: Y
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Bazel
        uses: actions/cache@v4
        with:
          path: ~/.cache/bazel
          key: bazel-${{ runner.os }}-${{ hashFiles('.bazelversion', 'MODULE.bazel', 'MODULE.bazel.lock') }}
          restore-keys: |
            bazel-${{ runner.os }}-

      - name: Test Core
        run: |
          bazel test //core/... --test_output=errors --keep_going

      - name: Summarize test logs on failure
        if: failure()
        run: |
          echo '--- BEGIN FAILED TEST LOGS (if any) ---'
          find bazel-testlogs -name "test.log" -type f -exec sh -c 'echo "::group::{}"; sed -e "s/\x1b\\[[0-9;]*m//g" "{}" | tail -n 200; echo "::endgroup::"' \; || true
          echo '--- END FAILED TEST LOGS ---'
